### PR TITLE
Added gps node

### PR DESCRIPTION
**Pull request by mattjay1024**
GPS node driver. Publishes position, heading, and status. 
#15

### CODE REVIEW

**Comment by EpicWolverine** [comment]
I'd really prefer you to change the package name to something like `vn300`.

**Comment by EpicWolverine** [comment]
Also update ReadMe.md with instructions for installing the library and include those changes in this pull request.

**Comment by EpicWolverine** [comment]
This is really good, but I would still really like the name changed before merging.

**Comment by EpicWolverine** [comment]
Just fix the readme to the point that people can install and run this just by following its instructions and I'll merge.

**Comment by danvanden** [comment]
MATT JUST DO IT!!!!!

**Comment by mattjay1024** [comment]
Isn't this already merged

**Comment by danvanden** [comment]
It is still under pull requests.

**Comment by EpicWolverine** [comment]
It'll get merged when you fix the readme

**Comment by mattjay1024** [comment]
Updated README to fix installation issues. **_Plz_** merge.

**Pull request merged**
